//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualData
    {
        public int ID { get; set; }
        public int BusNr { get; set; }
        public int LastStation { get; set; }
        public System.TimeSpan Time { get; set; }
    }
}
