//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusDBEntities1 : DbContext
    {
        public BusDBEntities1()
            : base("name=BusDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bus> Bus { get; set; }
        public virtual DbSet<BusTrace> BusTrace { get; set; }
        public virtual DbSet<Line> Line { get; set; }
        public virtual DbSet<Measurements> Measurements { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        public virtual DbSet<References> References { get; set; }
        public virtual DbSet<Timetable> Timetable { get; set; }
        public virtual DbSet<MeasuredData> MeasuredData { get; set; }
        public virtual DbSet<ActualData> ActualData { get; set; }
    }
}
