//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusDBEntities2 : DbContext
    {
        public BusDBEntities2()
            : base("name=BusDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BusPositions> Bus { get; set; }
        public virtual DbSet<BusTrace> BusTrace { get; set; }
        public virtual DbSet<Line> Line { get; set; }
        public virtual DbSet<Measurements> Measurements { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        
    }
}
